package br.unirio.yser.dblp;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import br.unirio.yser.model.Pesquisador;
import br.unirio.yser.model.Publicacao;

public class GeradorPublicacaoConjunta
{
	private static String[] CONVERSOES =
	{
		"Adenilso da Silva Simão",						"Adenilso Simão",
		"Adenilso Simao",								"Adenilso Simão",
		"Auri M. R. Vincenzi",							"Auri Vincenzi",
		"Auri Marcelo Rizzo Vincenzi",					"Auri Vincenzi",
		"Celso G. Camilo-Junior",						"Celso Camilo",
		"Celso Gonyalves Camilo-Junior",				"Celso Camilo",
		"Cássio L. Rodrigues", 							"Cássio Rodrigues",
		"Alessandro F. Garcia",							"Alessandro Garcia",
		"Cláudio Sant'Anna",							"Claudio Sant'Anna",
		"Arilo Claudio Dias Neto",						"Arilo Claudio",
		"Arilo Claudio Dias-Neto",						"Arilo Claudio",
		"Arilo Dias Neto",								"Arilo Claudio",
		"Otávio Augusto Lazzarini Lemos",				"Otávio Lemos",
		"Fabiano Cutigi Ferrari",						"Fabiano Ferrari",
		"Márcio Ribeiro", 								"Marcio Ribeiro",
		"Cleidson R. B. de Souza",						"Cleidson de Souza",
		"Cleidson Ronald Botelho de Souza",				"Cleidson de Souza",
		"Eduardo Santana De Almeida",					"Eduardo Almeida",
		"Daniela S. Cruzes", 							"Daniela Cruzes",
		"Leonardo Gresta Paulino Murta", 				"Leonardo Murta", 
		"Lucas C. Cordeiro", 							"Lucas Cordeiro",
		"Marcelo Dias de Amorim", 						"Marcelo D'Amorim",
		"Tiago Massoni",								"Tiago Lima Massoni",
		"Tiago Lima",									"Tiago Lima Massoni",
		"Sérgio C. B. Soares",							"Sérgio Soares",
		"Roberta de Souza Coelho",						"Roberta Coelho",
		"Djones Lettnin",								"Djones Vinicius Lettnin",
		"Karina R. G. da Silva",						"Karina Rocha",
		"Tayana Uchôa Conte",							"Tayana Conte",
		"Fernando Castor Filho",						"Fernando Castor",
		"Alessandro Fabricio Garcia",					"Alessandro Garcia",
		"Monalessa Perini Barcellos",					"Monalessa Barcelos",
		"Eduardo Magno Lages Figueiredo",				"Eduardo Figueiredo",
		"Raimundo da Silva Barreto",					"Raimundo Barreto",
		"Raimundo S. Barreto",							"Raimundo Barreto",

	};
	
	private static String[] IGNORAR = 
	{
		"A. C. B. Loureiro Moncao", 
		"A. César C. França", 
		"Adauto Almeida", 
		"Adenilso Petrenko", 
		"Adilson Luiz Bonifácio", 
		"Adolfo Rodriguez", 
		"Adriana Dantas", 
		"Adriano Albuquerque", 
		"Adriano L. I. de Oliveira", 
		"Adriano L. I. Oliveira", 
		"Adriano Lorena Inácio de Oliveira", 
		"Afonso Pimentel", 
		"Afonso Sales", 
		"Ahilton Barreto", 
		"Ahmed Sobeih", 
		"Alan Gavioli", 
		"Alan MacCormack", 
		"Alan R. Santos", 
		"Alberto Barbosa Raposo", 
		"Alberto Castro", 
		"Alberto Costa Neto", 
		"Alberto Raposo", 
		"Alcemir Santos", 
		"Alejandro César Frery", 
		"Alessandro Cavalcante Gurgel", 
		"Alessandro Marchetto", 
		"Alex Borges", 
		"Alex D. B. Alberto", 
		"Alexander B. Romanovsky", 
		"Alexander Grünhage", 
		"Alexander Romanovsky", 
		"Alexandre A. B. Lima", 
		"Alexandre Alvaro", 
		"Alexandre Ceolin Hausen", 
		"Alexandre Costa Martins", 
		"Alexandre de Melo Lima", 
		"Alexandre L. G. Damasceno", 
		"Alexandre Mota", 
		"Alexandre Petrenko", 
		"Alexandre Rodrigues", 
		"Alexandre Vasconcelos", 
		"Alexandre Vianna", 
		"Alexandru Tatar", 
		"Alfredo Goldman", 
		"Aline Alencar", 
		"Aline Carneiro Viana", 
		"Alline de Melo Lemos", 
		"Alysson A. Mendonca", 
		"Amadeu Anderlin Neto", 
		"Amanda Sávio Nascimento", 
		"Ambra Molesini", 
		"Américo Sampaio", 
		"Amira Ben Hamida", 
		"Ana C. L. Monção", 
		"Ana Candida Cruz Natali", 
		"Ana Liz S. Souto", 
		"Ana Luisa Medeiros", 
		"Ana Moreira", 
		"Ana Paula Carvalho Cavalcanti", 
		"Ana Paula Chaves", 
		"Ana Regina Cavalcanti da Rocha", 
		"Ana Regina Rocha", 
		"Analia Irigoyen Ferreiro Ferreira", 
		"Anarosa Brandão", 
		"Anderson Marinho", 
		"Andre Assis Lobo de Oliveira", 
		"André L. M. Santos", 
		"André Luis M. Santos", 
		"André Luis Schwerz", 
		"André Luiz Becker", 
		"André Luíz de Oliveira", 
		"André Mauricio Campos", 
		"André Sousa", 
		"André Takeshi Endo", 
		"André van der Hoek", 
		"André Wilson Brotto Furtado", 
		"Andréa Barreto", 
		"Andréa Magalhães Magdaleno", 
		"Andrea Menezes", 
		"Andrea Oliveira Soares Barreto", 
		"Andrea Omicini", 
		"Andrea P. Mendonça", 
		"Andréa Soares", 
		"Andreas Braun", 
		"Andreas Rummler", 
		"Andrei Rimsa", 
		"Andrew Diniz da Costa", 
		"Andrew T. Campbell", 
		"Anna Beatriz Marques", 
		"Anna Perini", 
		"Anne Elise Katsurayama", 
		"Anne Fladenmuller", 
		"Anselmo Antunes Montenegro", 
		"Anthony Finkelstein", 
		"Antonio C. Contieri Jr.", 
		"Antonio C. Contieri Junior", 
		"Antônio Carlos Lima de Santana", 
		"Antonio de Pádua Albuquerque Oliveira", 
		"Antônio Francisco do Prado", 
		"Antônio Perdigoto", 
		"Antônio Tadeu A. Gomes", 
		"Apostolos Zarras", 
		"Arnaldo Vieira Moura", 
		"Arnaud Limbourg", 
		"Arndt von Staa", 
		"Artur Ziviani", 
		"Augusta Marques", 
		"Augusto Sampaio", 
		"Aurélio A. M. Matsui", 
		"Aurélio da Silva Grande", 
		"Aurora Vizcaíno", 
		"Awais Rashid", 
		"Axel G. Braun", 
		"Ayres Mardem", 
		"Azriel Majdenbaum", 
		"Ban Al-Ani", 
		"Bedir Tekinerdogan", 
		"Benito Diaz Paret", 
		"Benito Fernandes", 
		"Benjamin Koehne", 
		"Bernd Fischer 0002", 
		"Bill Frakes", 
		"Bjørnar Tessem", 
		"Brittany Johnson", 
		"Bruna Ferreira", 
		"Bruno Barbieri Pontes Cafeo", 
		"Bruno Bonifácio", 
		"Bruno Brochado Ribeiro", 
		"Bruno Carreira Coutinho Silva", 
		"Bruno Carreiro da Silva", 
		"Bruno Catao", 
		"Bruno Gadelha", 
		"Bryan Clark", 
		"Caio A. N. Lima", 
		"Calebe De Paula Bianchini", 
		"Camila Nunes", 
		"Camila Ribeiro Rocha", 
		"Carina Frota Alves", 
		"Carla Delgado", 
		"Carla T. L. L. Silva", 
		"Carlon Halmenschlager Szymanski", 
		"Carlos André Guimarães Ferraz", 
		"Carlos Eduardo Albuquerque da Cunha", 
		"Carlos Eduardo Lima Peixoto", 
		"Carlos Eduardo Paulino", 
		"Carlos Eduardo Pontual", 
		"Carlos José Pereira de Lucena", 
		"Carlos Mar", 
		"Carlos Pacheco", 
		"Carmen Maidantchik", 
		"Carolyn B. Seaman", 
		"Cássio Teixeira", 
		"Catarina Costa", 
		"Catuxe Varjao", 
		"Cecília M. F. Rubira", 
		"Cecília Mary Fischer Rubira", 
		"Célio Santana", 
		"Cesar A. L. Oliveira", 
		"Cesar Couto", 
		"Chang Hwan Peter Kim", 
		"Chessman K. F. Corrêa", 
		"Christa Schwanninger", 
		"Christiane Gresse von Wangenheim", 
		"Christina Chavez", 
		"Christina von Flach G. Chavez", 
		"Christof Ebert", 
		"Christoph Pohl", 
		"Cidiane Lobato", 
		"Claes Wohlin", 
		"Claude Chaudet", 
		"Cláudia Maria Lima Werner", 
		"Cláudia Souza", 
		"Claudia Susie C. Rodrigues", 
		"Cláudia Werner", 
		"Claudio Haruo Yamamoto", 
		"Claudio S. Pinhanez", 
		"Claus Brabrand", 
		"Cleber R. P. da Rocha", 
		"Cleice Souza", 
		"Cleviton V. F. Monteiro", 
		"Cleyton Mário de Oliveira Rodrigues", 
		"Clovis Torres Fernandes", 
		"Corina S. Pasareanu", 
		"Crescencio Lima", 
		"Crescencio Rodrigues Lima Neto", 
		"Cristiano Bertolini", 
		"Cristina Araújo", 
		"Cristina Cerdeiral", 
		"Cristina Videira Lopes", 
		"Cristine Gusmão", 
		"Cristine R. Dantas", 
		"Crys S. Goto", 
		"D. Serey", 
		"Dalcykelem B. Santos", 
		"Dali Li", 
		"Dalton Dario Serey Guerrero", 
		"Dalton S. Guerrero", 
		"Dalton Serey Guerrero", 
		"Dalton Vilela", 
		"Daltro José Nunes", 
		"Daniel Alencar da Costa", 
		"Daniel Branco", 
		"Daniel Carnio Junqueira", 
		"Daniel de Oliveira", 
		"Daniel Jackson", 
		"Daniel Lucrédio", 
		"Daniel Macedo Batista", 
		"Daniel Patrick", 
		"Daniel Popescu", 
		"Daniel Schneider", 
		"Daniel Wildt", 
		"Daniela Damian", 
		"Danielle Medeiros", 
		"Danny Weyns", 
		"Dante Carlos Antunes", 
		"Danuza Ferreira Santana Neiva", 
		"Dárcio Prestes", 
		"Darko Marinov", 
		"Davi Viana", 
		"David Chenho Kung", 
		"David F. Redmiles", 
		"David H. Bushnell", 
		"David Leonardo M. Bentolila", 
		"David R. Millen", 
		"David Simplot-Ryl", 
		"David Weiss", 
		"David Zanetti", 
		"Débora Maurmo Modesto", 
		"Dejan S. Milojicic", 
		"Delano M. Beder", 
		"Demóstenes Sena", 
		"Denis Nicole", 
		"Denise Filippo", 
		"Diego Cavalcanti", 
		"Diego Lima", 
		"Diego Saraiva", 
		"Diogo B. Brum", 
		"Diogo Santana", 
		"Dirk Muthig", 
		"Djoni Antonio da Silva", 
		"Don S. Batory", 
		"Donald D. Cowan", 
		"Douglas Siqueira Leite", 
		"Ed Zaluska", 
		"Eddie B. L. Filho", 
		"Edmilson Campos Neto", 
		"Edmundo Sérgio Spoto", 
		"Edna Magalhães", 
		"Ednaldo Dilorenzo de Souza Filho", 
		"Edson A. Oliveira Jr.", 
		"Edson Alves de Oliveira Junior", 
		"Eduardo Aranha", 
		"Eduardo Bezerra", 
		"Eduardo Cruz Reis Santos", 
		"Eduardo Laureano", 
		"Eduardo Martins Guerra", 
		"Eduardo Piveta", 
		"Eduardo S. Ogasawa", 
		"Eduardo S. Ogasawara", 
		"Eduardo Silva", 
		"Eduardo T. Sawabe", 
		"Eduardo Valentin", 
		"Eiji Adachi Barbosa", 
		"Elaine Duarte", 
		"Elder Cirilo", 
		"Elena Jurado", 
		"Eliane Collins", 
		"Eliane Martins", 
		"Elisa L. A. Baniassad", 
		"Elisa Yumi Nakagawa", 
		"Ellen Francine Barbosa", 
		"Ellen W. Zegura", 
		"Ellie D'Hondt", 
		"Elmar U. K. Melcher", 
		"Elthon A. S. Oliveira", 
		"Elton Alves", 
		"Emanoel Barreiros", 
		"Emelie Engström", 
		"Emerson R. Murphy-Hill", 
		"Emilia Mendes", 
		"Eric Platon", 
		"Erick Baptista Passos", 
		"Erik Trainer", 
		"Erika Nina Höhn", 
		"Erran Carmel", 
		"Esteban Walter Gonzalez Clua", 
		"Estevão Ricardo Hess", 
		"Esther Brasileiro", 
		"Eudisley Gomes dos Anjos", 
		"Euler Horta Marinho", 
		"Everton Guimãraes", 
		"Fabian Vargas", 
		"Fabiano Cruz", 
		"Fabio Calefato", 
		"Fabio Fagundes Silveira", 
		"Fabio Jorge Morais", 
		"Fabio Kon", 
		"Fábio M. Costa", 
		"Fábio Protti", 
		"Fabio Q. B. da Silva", 
		"Fábio Santos", 
		"Farid Benbadis", 
		"Fehmi Ben Abdesslem", 
		"Felipe Alves", 
		"Felipe Farias Maciel", 
		"Felipe Nunes Gaia", 
		"Felipe Pinto", 
		"Felipe Queiroz", 
		"Felipe S. Sarmanho", 
		"Felipe Sousa", 
		"Fellipe Araújo Aleixo", 
		"Felype Ferreira", 
		"Feng Chen", 
		"Fernanda M. R. Alencar", 
		"Fernando Calheiros", 
		"Fernando Cesar de Almeida", 
		"Fernando Magno Quintão Pereira", 
		"Fernando Peres", 
		"Fernando R. C. Silva", 
		"Fernando Raposo da Camara Silva", 
		"Fernando Rocha", 
		"Fernando Seabra Chirigati", 
		"Fevzi Belli", 
		"Filipe Alencar Ximenes", 
		"Filipe Lima", 
		"Filippo Lanubile", 
		"Flávia Coimbra Delicato", 
		"Flavio Lima", 
		"Flavio Lyra", 
		"Flávio M. Medeiros", 
		"Flávio Oquendo", 
		"Florian Heidenreich", 
		"Florian Klein", 
		"Forrest Shull", 
		"Francisco Dantas", 
		"Francisco José da Silva e Silva", 
		"Francisco Soares-Neto", 
		"Francisco W. Santana", 
		"Franck Legendre", 
		"Franco Zambonelli", 
		"François Taïani", 
		"Frank Maurer", 
		"Frederico Araujo Durão", 
		"Frederico Lopes", 
		"Frederico T. de Oliveira", 
		"Gabriel Coutinho Sousa Ferreira", 
		"Gabriel Falconieri", 
		"Gabriel Falconieri Freitas", 
		"Geber L. Ramalho", 
		"Geber Ramalho", 
		"Gecynalda Soares da Silva Gomes", 
		"Genaína Nunes Rodrigues", 
		"Geoff Coulson", 
		"George Heineman", 
		"George Valença", 
		"Geraldo Zimbrao", 
		"Gina Venolia", 
		"Gisele Macedo", 
		"Gisele Rodrigues Mesquita Ferreira", 
		"Gladys Machado Pereira S. Lima", 
		"Glaucia Peres", 
		"Glauco de Figueiredo Carneiro", 
		"Gleydson Lima", 
		"Gloria Mark", 
		"Golnaz Karbaschi", 
		"Gordon S. Blair", 
		"Graça Bressan", 
		"Greg Bigwoodt", 
		"Grigore Rosu", 
		"Guilherme G. Correia", 
		"Guilherme Horta Travassos", 
		"Guilherme M. Nogueira", 
		"Guilherme Travassos", 
		"Guillaume Chelius", 
		"Gustavo Ansaldi Oliva", 
		"Gustavo Bittencourt Figueiredo", 
		"Gustavo Honorato", 
		"Gustavo Lima", 
		"Gustavo Pinto", 
		"Gustavo Sizílio", 
		"Gustavo Soares", 
		"Guy Pujolle", 
		"Hajime Tazaki", 
		"Hamilton L. R. Oliveira", 
		"Heberth Braga G. Ribeiro", 
		"Heike Winshiers-Theophilus", 
		"Heitor Costa", 
		"Heitor Mariano", 
		"Heitor Vital", 
		"Helen Sharp", 
		"Hendrio Marques", 
		"Henrique do N. Cunha", 
		"Henrique Luiz Cukierman", 
		"Henrique Rebêlo", 
		"Herbert Rocha", 
		"Hilário Tomaz", 
		"Hítalo Oliveira da Silva", 
		"Ho-fung Leung", 
		"Holger Giese", 
		"Hong Yul Yang", 
		"Horacio A. B. F. de Oliveira", 
		"Horácio A. B. F. Oliveira", 
		"Huan Chen 0001", 
		"Hugo Estrada-Esquivel", 
		"Hugo Fuks", 
		"Hugo Melo", 
		"Ignacio Solis", 
		"Igor Scaliante Wiese", 
		"Igor Steinmacher", 
		"Ilmari Ceccato", 
		"Ingrid Costa", 
		"Ingrid Nunes", 
		"Ioannis Stavrakakis", 
		"Isabel John", 
		"Isabelle Guérin Lassous", 
		"Isela Macia Bertran", 
		"Ismênia Galvão", 
		"Ita Richardson", 
		"Itana Maria de Souza Gimenes", 
		"Iuri Santos Souza", 
		"Ivaldir H. de Farias Junior", 
		"Ivan Cardim", 
		"Ivan do Carmo Machado", 
		"Ivan Gustavo Franchin", 
		"Ivonei Freitas da Silva", 
		"J. Ignacio Alvarez-Hamelin", 
		"J. Roberto Evaristo", 
		"Jacilane Rabelo", 
		"Jacques Noyé", 
		"Jacques Wainer", 
		"Jadson Santos", 
		"Jaejoon Lee", 
		"Jaelson Brelaz de Castro", 
		"Jaelson Castro", 
		"Jailton Louzada", 
		"Jair Cavalcanti Leite", 
		"Jair S. Ferreira Jr.", 
		"Jairo Avritchir", 
		"Jairson M. Cabral", 
		"Jalerson Lima", 
		"James Noble", 
		"Janice Singer", 
		"Jaqueline Faria", 
		"Jardelane Brito", 
		"Jarley Palmeira Nóbrega", 
		"Jean Marcel dos Reis Costa", 
		"Jean-Claude Royer", 
		"Jean-Jacques Puig", 
		"Jean-Loup Guillaume", 
		"Jeff Gray", 
		"Jefferson Silva de Amorim", 
		"Jennifer C. Hou", 
		"Jeremie Leguay", 
		"Jeremy Morse", 
		"Jianjun Zhao", 
		"Jie Xu", 
		"Jin Ying", 
		"Joachim Gerlach", 
		"João Araújo 0001", 
		"João Eduardo Ferreira", 
		"João Gustavo Prudêncio", 
		"João Marques-Silva", 
		"João P. Marques Silva", 
		"João Paulo Oliveira", 
		"João Pedro Santos", 
		"Joás Sousa Gomes", 
		"Jobson Luiz Massolar da Silva", 
		"Joel Ossher", 
		"Johan Brichau", 
		"John D. McGregor", 
		"John F. Patterson", 
		"John Penix", 
		"John W. Stamey", 
		"John Whitbeck", 
		"Jon Crowcroft", 
		"Jon Froehlich", 
		"Jon Whittle", 
		"Jonathan Sillito", 
		"Jonhnny Weslley S. Sousa", 
		"Joost Noppen", 
		"Jörg Behrend", 
		"Jorge C. A. de Figueiredo", 
		"Jorge Calmon de Almeida Biolchini", 
		"Jorge Cláudio Cordeiro Pires Mascena", 
		"Jorge Luis Nicolas Audy", 
		"José Alberto R. P. Sardinha", 
		"José Antonio Antonioni", 
		"José Carlos Maldonado", 
		"José Elias Araújo", 
		"José Ferreira de Rezende", 
		"José Herrera", 
		"José Jorge Lima Dias Junior", 
		"José María Conejero", 
		"José Raimundo Pereira", 
		"Jose Ricardo da Silva Junior", 
		"Jose Teodoro da Silva", 
		"Joshua Garcia", 
		"Josiane Kroll", 
		"Juan Hernández", 
		"Jucele Vasconcellos", 
		"Juliana Lucena", 
		"Juliana Saraiva", 
		"Juliano Iyoda", 
		"Julinda Stefa", 
		"Julio Cesar Sampaio do Prado Leite", 
		"Jun Murai", 
		"Jürgen Ruf", 
		"Kanchana Kanchanasut", 
		"Kanwarpreet Sethi", 
		"Kari Rönkkö", 
		"Karin Breitman", 
		"Karina Villela", 
		"Karla Damasceno", 
		"Káthia Marçal de Oliveira", 
		"Katia Obraczka", 
		"Keerthana Boloor", 
		"Kellyton dos Santos Brito", 
		"Kevin J. Sullivan", 
		"Kival Chaves Weber", 
		"Klaus Havelund", 
		"Klaus Schmid", 
		"Kléder Miranda Gonçalves", 
		"Kleinner Farias", 
		"Kleverton C. M. de Oliveira", 
		"Klissiomara L. Dias", 
		"Konstantin Kabassanov", 
		"Laís Neves", 
		"Larissa Leite", 
		"Laura Galluccio", 
		"Laurence Tianruo Yang", 
		"Leandra Mara", 
		"Leandro Dantas Calvao", 
		"Leandro F. Nascimento", 
		"Leandro Lopes", 
		"Leandro Marques Nascimento", 
		"Leandro Max L. Silva", 
		"Len Bass", 
		"Leonardo A. F. Leite", 
		"Leonardo Cole", 
		"Leonardo P. Tizzei", 
		"Leonardo Pilatti", 
		"Leonardo Santos", 
		"Leonardo T. Queiroz", 
		"Leonidas Tzevelekas", 
		"Leopoldo Ferreira", 
		"Leopoldo Teixeira", 
		"Lian Yu", 
		"Liana Barachisio Lisboa", 
		"Liana Silva", 
		"Lidia Fuentes", 
		"Lílian Schnaider", 
		"Li-Te Cheng", 
		"Luanna Lopes Lobato", 
		"Luca Sabatucci", 
		"Lucas Pereira", 
		"Lucas Santos de Oliveira", 
		"Lucas Welter Hilgert", 
		"Luciano Barbosa", 
		"Luciano José Senger", 
		"Lucinéia Turnes", 
		"Lúcio Ribeiro", 
		"Ludymila Gomes", 
		"Luigi Buglione", 
		"Luigi Iannone", 
		"Luís Carlos Trevelin", 
		"Luís Henrique Maciel Kosmalski Costa", 
		"Luís Henrique Raja Gabaglia Mitchell", 
		"Luis Jorge Enrique Rivero Cabrejos", 
		"Luis Rivero", 
		"Luiz A. Laranjeira", 
		"Luiz Arthur F. Santos", 
		"Luiz Fortaleza", 
		"Luiz Gustavo Lopes", 
		"Luiz Laerte Nunes da Silva Jr.", 
		"Luiz Marcio Cysneiros", 
		"Lyrene Fernandes da Silva", 
		"M. Cecilia Bastarrica", 
		"Maarten Sierhuis", 
		"Mahesh Viswanathan", 
		"Maicon G. Pazin", 
		"Maíra A. de C. Gatti", 
		"Maíra Paschoalino", 
		"Manoel G. Mendonça", 
		"Marcel Vinicius Medeiros Oliveira", 
		"Marcela Balbino", 
		"Marcelio D'Oliveira Leal", 
		"Marcello Macarthy", 
		"Marcelo Blois Ribeiro", 
		"Marcelo Cataldo", 
		"Marcelo de Almeida Maia", 
		"Marcelo Fantinato", 
		"Marcelo Finger", 
		"Marcelo Hideki Yamaguti", 
		"Marcelo Medeiros Eler", 
		"Marcelo Nery dos Santos", 
		"Marcelo Oliveira Dias", 
		"Marcelo Schots", 
		"Marcelo Zilio Pereira", 
		"Márcio de Oliveira Barros", 
		"Márcio Eduardo Delamaro", 
		"Marcio K. Goncalves", 
		"Márcio Pecegueiro do Amaral", 
		"Marco A. S. Mangan", 
		"Marco Antonio Balieiro", 
		"Marco Aurélio Graciotto Silva", 
		"Marco Aurélio Stelmar Netto", 
		"Marco Autili", 
		"Marco Tulio Valente", 
		"Marco Valerio Barbera", 
		"Marcos Dias de Assunção", 
		"Marcos Dósea", 
		"Marcos Gomes", 
		"Marcos Kalinowski", 
		"Marcos Lordello Chaim", 
		"Marcos Oliveira", 
		"Marcos R. S. Borges", 
		"Marcos Silva", 
		"Marcus Vinicius Couto", 
		"Margaret-Anne D. Storey", 
		"Maria Beatriz Felgar de Toledo", 
		"Maria Carolina Monard", 
		"Maria Cristina Felippetto de Castro", 
		"Maria Lencastre", 
		"Mariane Aoki", 
		"Mariângela Vanzin", 
		"Mariano Cravo", 
		"Mariano Gomes Pimentel", 
		"Mariano Montoni", 
		"Mariela M. F. Sasaki", 
		"Marília Aranha Freire", 
		"Mario C. C. Machado", 
		"Mario Freitas da Silva", 
		"Mário Henrique C. Torres", 
		"Mario Jino", 
		"Mario Monteiro", 
		"Mário S. Camillo", 
		"Mario Südholt", 
		"Mário Zenha Rela", 
		"Markus Winterholer", 
		"Marlon Vieira", 
		"Marta Mattoso", 
		"Martin Becker 0002", 
		"Martin Bogdan", 
		"Martin L. Griss", 
		"Maryanne P. Rosa", 
		"Massimo Cossentino", 
		"Mateus Borges", 
		"Matheus Sousa", 
		"Matheus Souza", 
		"Mathias Boc", 
		"Matthew J. Bietz", 
		"Mauricio Alférez", 
		"Mauricio Cristal", 
		"Mauricio Finavaro Aniche", 
		"Mauro Biajiz", 
		"Mauro Freitas", 
		"Mauro Teófilo", 
		"Mayara Figueiredo", 
		"Mehdi Bezahaf", 
		"Mehmet Aksit", 
		"Melina Mongiovi", 
		"Meuse N. Oliveira Jr.", 
		"Michael D. Ernst", 
		"Michael da Costa Móra", 
		"Michael Eichberg", 
		"Michael Haupt", 
		"Michael John", 
		"Michael Linschulte", 
		"Michal Young", 
		"Michalis Anastasopoulos", 
		"Michel Abdalla", 
		"Miguel Elias M. Campista", 
		"Mihail L. Sichitiu", 
		"Mikhail Ramalho", 
		"Mikko Korpela", 
		"Milos Gligoric", 
		"Mira Mezini", 
		"Mitsuo Takaki", 
		"Mostafa H. Ammar", 
		"Nabor C. Mendonça", 
		"Nadjet Belblidia", 
		"Naftaly H. Minsky", 
		"Nan Niu", 
		"Natasha M. Costa Valentim", 
		"Nathalia Temudo", 
		"Nathalie Mitton", 
		"Nayane Maia", 
		"Neil Loughran", 
		"Nélio Cacho", 
		"Nelly Bencomo", 
		"Nenad Medvidovic", 
		"Nicolas Anquetil", 
		"Nicolas Pauvre", 
		"Nikolaos Georgantas", 
		"Nina Yevtushenko", 
		"Odette Mestrinho Passos", 
		"Olavo Matos", 
		"Oliver Bringmann", 
		"Orit Hazzan", 
		"Orlando Loques", 
		"Otavio Silva", 
		"Otto Carlos M. B. Duarte", 
		"Otto Carlos Muniz Bandeira Duarte", 
		"P. de Sa Leitao-Junior", 
		"Pablo Sánchez", 
		"Pádraig O'Leary", 
		"Panayotis Antoniadis", 
		"Panos Vassiliadis", 
		"Paola R. G. Accioly", 
		"Paolo Giorgini", 
		"Patrícia D. L. Machado", 
		"Patrícia Lustosa", 
		"Patrícia Machado", 
		"Patrick H. S. Brito", 
		"Patrick Heckeler", 
		"Patrick Henrique da S. Brito", 
		"Paul C. Clements", 
		"Paul Dourish", 
		"Paul Grace", 
		"Paul Rayson", 
		"Paula Fernandes", 
		"Paula Gomes Mian", 
		"Paula Gonçalves Ferreira", 
		"Paulo Anselmo da Mota Silveira Neto", 
		"Paulo Asterio de Castro Guerra", 
		"Paulo Barros", 
		"Paulo Borba", 
		"Paulo Cavalcanti", 
		"Paulo Cesar Masiero", 
		"Paulo César Masiero", 
		"Paulo E. S. Barbosa", 
		"Paulo F. Pires", 
		"Paulo Henrique Lemelle Fernandes", 
		"Paulo Romero Martins Maciel", 
		"Paulo S. C. Alencar", 
		"Paulo Sergio Lopes de Souza", 
		"Paulo Sérgio Medeiros dos Santos", 
		"Pedro Freitas", 
		"Pedro H. M. Sampaio", 
		"Pedro J. F. Treccani", 
		"Pedro Matos", 
		"Pedro Matos Jr.", 
		"Pedro Santos Neto", 
		"Pedro Teles", 
		"Per Runeson", 
		"Percy E. Salas", 
		"Pericles Alves", 
		"Peter Gober", 
		"Peter Lupo", 
		"Peter Sawyer", 
		"Petia Todorova", 
		"Phil Greenwood", 
		"Philipp Hünerberg", 
		"Philippe Kruchten", 
		"Pierre Baldi", 
		"Pierre-Ugo Tournoux", 
		"Pim van den Broek", 
		"Plínio de Sá Leitão-Jr", 
		"Pradeep Kumar Nalla", 
		"Priscila Fernandes", 
		"Prométhée Spathis", 
		"Rachel Burrows", 
		"Rafael A. Glanzner", 
		"Rafael Barcellos", 
		"Rafael Barcelos", 
		"Rafael Cunha", 
		"Rafael da Silva Viterbo de Cepêda", 
		"Rafael de Souza Santos", 
		"Rafael Di Bernardo", 
		"Rafael Farias", 
		"Rafael Liberato", 
		"Rafael Martins Feitosa", 
		"Rafael Pinho", 
		"Rafael Pinto Medeiros", 
		"Rafael Scheidt", 
		"Rajesh Subramanyan", 
		"Ralf Lämmel", 
		"Ralf Mitschke", 
		"Ramon Abílio", 
		"Raoni Kulesza", 
		"Raphael Pereira de Oliveira", 
		"Raphael Y. de Camargo", 
		"Raquel de A. Maranhão Ferreira", 
		"Raquel Maranhão", 
		"Rashina Hoda", 
		"Raul Adrian Gorcitz", 
		"Regina M. M. Braga", 
		"Reginaldo Ré", 
		"Regine Meunier", 
		"Reinaldo Cabral", 
		"Reinaldo Cabral Silva Filho", 
		"Renata Medeiros", 
		"Renata P. M. Fortes", 
		"Renata Pontin de Mattos Fortes", 
		"Renata Vieira", 
		"Renato B. Abreu", 
		"Renato Franklin", 
		"Renato Lima Novais", 
		"Renato Silveira", 
		"Ricardo Araujo Costa", 
		"Ricardo Argenton Ramos", 
		"Ricardo Bastos Cavalcante Prudêncio", 
		"Ricardo Choren", 
		"Ricardo de A. Araújo", 
		"Ricardo de Oliveira Cavalcanti", 
		"Ricardo M. Czekster", 
		"Ricardo Massa Ferreira Lima", 
		"Ricardo Mateus", 
		"Ricardo Sales Jr.", 
		"Ricardo Santos Morla", 
		"Rita Almeida Ribeiro", 
		"Robert D. Callaway", 
		"Robert J. Walker", 
		"Robert Seater", 
		"Roberta Arcoverde", 
		"Roberta Cerqueira", 
		"Roberto da Silva Bigonha", 
		"Roberto Quilez", 
		"Roberto Silveira Silva Filho", 
		"Robson Pinheiro", 
		"Robson Ytallo Silva de Oliveira", 
		"Rodney Van Meter", 
		"Rodrigo Bonifácio", 
		"Rodrigo Campiolo", 
		"Rodrigo Fernandes de Mello", 
		"Rodrigo G. C. Rocha", 
		"Rodrigo Miranda", 
		"Rodrigo P. M. de Araújo", 
		"Rodrigo Pereira dos Santos", 
		"Rodrigo Santos de Espindola", 
		"Rogério de Lemos", 
		"Rogério do Nascimento", 
		"Roland J. Weiss", 
		"Ronald Vargas", 
		"Roni A. Dall Orsoletta", 
		"Rosana T. V. Braga", 
		"Rosângela Aparecida Dellosso Penteado", 
		"Rosangela Penteado", 
		"Roseli Aparecida Francelin Romero", 
		"Rosiane de Freitas Rodrigues", 
		"Rosiane Rodrigues", 
		"Ruy Luiz Milidiú", 
		"Ruzanna Chitchyan", 
		"Ryan Ribeiro de Azevedo", 
		"Ryuji Wakikawa", 
		"Saavio Rodrigues Cavalcanti", 
		"Sabrina Marczak", 
		"Sabrina Souto", 
		"Safoora Shakil Khan", 
		"Salvatore Gaglio", 
		"Samuel Felix de Sousa Jr.", 
		"Sandra Ferrari", 
		"Sandro Ronaldo Bezerra Oliveira", 
		"Sara Hachem", 
		"Sarfraz Khurshid", 
		"Saswat Anand", 
		"Sávio Figueiredo", 
		"Sebastiao B. Fonseca", 
		"Serge Fdida", 
		"Sérgio Manuel Serra da Cruz", 
		"Sergio Palazzo", 
		"Sérgio Roberto Costa Vieira", 
		"Sérgio T. Carvalho", 
		"Shmuel Katz", 
		"Silvia Regina Vergilio", 
		"Silvio R. L. Meira", 
		"Silvio Romero de Lemos Meira", 
		"Simone da Silva Amorim", 
		"Simone do Rocio Senger de Souza", 
		"Sindolfo Miranda Filho", 
		"Siobhán Clarke", 
		"Solon Aguiar", 
		"Sômulo Mafra", 
		"Stefan Huster", 
		"Steffen Zschaler", 
		"Stephan Reitemeyer", 
		"Stephen Quirk", 
		"Steven I. Ross", 
		"Steven Lauterburg", 
		"Straus Michalsky", 
		"Stuart R. Faulk", 
		"Sunita Chulani", 
		"Sunny Wong", 
		"Susan Elliott Sim", 
		"Susanne Hupfer", 
		"Sushil Krishna Bajracharya", 
		"Svein O. Hallsteinsen", 
		"Taciana A. Vanderlei", 
		"Tahiry Razafindralambo", 
		"Tanmay Bhowmik", 
		"Tao Xie", 
		"Tarcisio Camara", 
		"Társis Tolêdo", 
		"Tássia Freitas", 
		"Tassio Vale", 
		"Tatiana Sugeta", 
		"Thais Eblíng", 
		"Thaís Ebling", 
		"Thaís Vasconcelos Batista", 
		"Thais Webber", 
		"Thelma Elita Colanzi", 
		"Thiago B. L. Silva", 
		"Thiago Bliscosque Goncalves", 
		"Thiago Fernandes Lins de Medeiros", 
		"Thiago Henrique Burgos de Oliveira", 
		"Thiago Jabur Bittar", 
		"Thiago Nazareth de Oliveira Alexandre Plastino", 
		"Thiago T. Bartolomei", 
		"Thirapon Wongsaardsakul", 
		"Thomas Begin", 
		"Thomas Claveirole", 
		"Thomas Cottenier", 
		"Thomas Kropf", 
		"Tihomir Gvero", 
		"Timur Friedman", 
		"Tiphaine Phe-Neau", 
		"Toacy Cavalcante de Oliveira", 
		"Tobias Hildenbrand", 
		"Tobias Kirsten", 
		"Tom Holvoet", 
		"Tomoji Kishi", 
		"Toni Pacheco", 
		"Tore Dybå", 
		"Troy C. Kohwalter", 
		"Uéverton dos Santos Souza", 
		"Valérie Issarny", 
		"Valter Vieira de Camargo", 
		"Vanessa Braganholo", 
		"Vanessa P. Braganholo", 
		"Vania Conan", 
		"Vanilson Arruda Burégio", 
		"Vasco Amaral", 
		"Verônica T. Vaz", 
		"Vicente Ferreira de Lucena Jr.", 
		"Vicente Lucena", 
		"Vicente Lustosa Neto", 
		"Victor Cavalcante", 
		"Victor F. Cavalcante", 
		"Victor H. Fernandes", 
		"Victor M. Gonzalez", 
		"Vilas Jagannath", 
		"Vilmar Nepomuceno", 
		"Vincent Borrel", 
		"Vinicius Asta Pagano", 
		"Vinicius Cardoso Garcia", 
		"Vinicius H. S. Durelli", 
		"Vinicius Nunes", 
		"Vítor Silva", 
		"Viviane Gomes", 
		"Viviane Torres da Silva", 
		"Volker Schönknecht", 
		"W. Eric Wong", 
		"Walter Cazzola", 
		"Wanderson Câmara dos Santos", 
		"Wesley Silva", 
		"Weslley Torres", 
		"Willian N. Oizumi", 
		"Wolfgang Rosenstiel", 
		"Wouter Joosen", 
		"Wylliams Barbosa Santos", 
		"Yael Dubinsky", 
		"Yannis Viniotis", 
		"Yesid Jarma", 
		"Yguaratã Cerqueira Cavalcanti", 
		"Yi Wang 0013", 
		"Yoann Lopez", 
		"Yuanfang Cai", 
		"Yvonne Dittrich", 
		"Zhang Rui", 
	};
	
	public void executa(List<Pesquisador> pesquisadores)
	{
		for (Pesquisador pesquisador : pesquisadores)
		{
			List<String> coAutores = new ArrayList<String>();
			
			for (Publicacao publicacao : pesquisador.pegaPublicacoes())
				for (String coAutor : publicacao.getAutores())
				{
					String coAutorConvertido = converteNome(coAutor);
					
					if (coAutorConvertido != null)
						coAutores.add(coAutorConvertido);
				}
			
			if (coAutores.size() > 0)
			{
				Collections.sort(coAutores);
				String ultimoCoAutor = coAutores.get(0);
				int contador = 1;
				
				for (int i = 1; i < coAutores.size(); i++)
				{
					String coAutor = coAutores.get(i);
					
					if (ultimoCoAutor.compareToIgnoreCase(coAutor) == 0)
					{
						contador++;
					}
					else
					{
						if (ultimoCoAutor.compareToIgnoreCase(pesquisador.getNome()) != 0)
							System.out.println(pesquisador.getNome() + "\t" + ultimoCoAutor + "\t" + contador);
						
						ultimoCoAutor = coAutor;
						contador = 1;
					}
				}
				
				if (ultimoCoAutor.compareToIgnoreCase(pesquisador.getNome()) != 0)
					System.out.println(pesquisador.getNome() + "\t" + ultimoCoAutor + "\t" + contador);
			}
		}
	}
	
	private String converteNome(String nome)
	{
		for (int i = 0; i < IGNORAR.length; i++)
			if (nome.compareToIgnoreCase(IGNORAR[i]) == 0)
				return null;
		
		for (int i = 0; i < CONVERSOES.length; i += 2)
			if (nome.compareToIgnoreCase(CONVERSOES[i]) == 0)
				return CONVERSOES[i+1];
		
		return nome;
	}
}